name: Terraform Apply

on:
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write

jobs:  
  dev-plan:
    runs-on: ubuntu-latest
    env:
      TF_VAR_environment: dev
      TF_VAR_app_name: ${{ vars.TF_VAR_APP_NAME }}
      TF_VAR_region: ${{ secrets.OCI_REGION }}
      BACKEND_CONFIG_BUCKET: ${{ secrets.BACKEND_CONFIG_BUCKET }}
      BACKEND_CONFIG_NAMESPACE: ${{ secrets.BACKEND_CONFIG_NAMESPACE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Write Config & Key Files'
        run: |
          mkdir -p ~/.oci
          echo "${{ secrets.OCI_CONFIG_FILE }}" | tee ~/.oci/config > /dev/null
          echo "${{ secrets.OCI_KEY_FILE }}" | tee ~/.oci/oci_api_key.pem > /dev/null
          chmod 600 ~/.oci/config ~/.oci/oci_api_key.pem
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest
      
      - name: Configure Terraform plugin cache
        run: |
          echo "TF_PLUGIN_CACHE_DIR=$HOME/.terraform.d/plugin-cache" >>"$GITHUB_ENV"
          mkdir --parents "$HOME/.terraform.d/plugin-cache"
          
      - name: Cache Terraform
        uses: actions/cache@v4
        with:
          path: |
            ~/.terraform.d/plugin-cache
          key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            terraform-${{ runner.os }}-

      - name: Terraform Init
        run: terraform init -backend-config="bucket=$BACKEND_CONFIG_BUCKET" -backend-config="namespace=$BACKEND_CONFIG_NAMESPACE" -backend-config="key=statefile/$TF_VAR_region/$TF_VAR_app_name/$TF_VAR_environment.tfstate"
        

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file="inputs/$TF_VAR_environment.tfvars" -out="tfplan-$TF_VAR_environment"

      - name: Cache Terraform Plan
        uses: actions/cache/save@v4
        with:
          path: tfplan-$TF_VAR_environment
          key: tfplan-${{ github.run_id }}-$TF_VAR_environment

  dev-apply:
    runs-on: ubuntu-latest
    needs: dev-plan
    environment: dev
    env:
      TF_VAR_environment: dev
      TF_VAR_app_name: ${{ vars.TF_VAR_APP_NAME }}
      TF_VAR_compartment_ocid: ${{ secrets.TF_VAR_COMPARTMENT_OCID_DEV }}
      TF_VAR_region: ${{ secrets.OCI_REGION }}
      BACKEND_CONFIG_BUCKET: ${{ secrets.BACKEND_CONFIG_BUCKET }}
      BACKEND_CONFIG_NAMESPACE: ${{ secrets.BACKEND_CONFIG_NAMESPACE }}

    steps:   
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Write Config & Key Files'
        run: |
          mkdir -p ~/.oci
          echo "${{ secrets.OCI_CONFIG_FILE }}" | tee ~/.oci/config > /dev/null
          echo "${{ secrets.OCI_KEY_FILE }}" | tee ~/.oci/oci_api_key.pem > /dev/null
          chmod 600 ~/.oci/config ~/.oci/oci_api_key.pem
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest
      
      - name: Configure Terraform plugin cache
        run: |
          echo "TF_PLUGIN_CACHE_DIR=$HOME/.terraform.d/plugin-cache" >>"$GITHUB_ENV"
          mkdir --parents "$HOME/.terraform.d/plugin-cache"
          
      - name: Cache Terraform
        uses: actions/cache@v4
        with:
          path: |
            ~/.terraform.d/plugin-cache
          key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            terraform-${{ runner.os }}-
      
      - name: Terraform Init
        run: terraform init -backend-config="bucket=$BACKEND_CONFIG_BUCKET" -backend-config="namespace=$BACKEND_CONFIG_NAMESPACE"  -backend-config="key=statefile/$TF_VAR_region/$TF_VAR_app_name/$TF_VAR_environment.tfstate"

      - name: Restore Plan Cache
        uses: actions/cache/restore@v4
        with:
          path: tfplan-$TF_VAR_environment
          key: tfplan-${{ github.run_id }}-$TF_VAR_environment
          fail-on-cache-miss: true

      - name: Terraform Apply
        run: terraform apply tfplan-$TF_VAR_environment

  uat-plan:
    runs-on: ubuntu-latest
    needs: [dev-apply]
    env:
      TF_VAR_environment: uat
      TF_VAR_app_name: ${{ vars.TF_VAR_APP_NAME }}
      TF_VAR_region: ${{ secrets.OCI_REGION }}
      BACKEND_CONFIG_BUCKET: ${{ secrets.BACKEND_CONFIG_BUCKET }}
      BACKEND_CONFIG_NAMESPACE: ${{ secrets.BACKEND_CONFIG_NAMESPACE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Write Config & Key Files'
        run: |
          mkdir -p ~/.oci
          echo "${{ secrets.OCI_CONFIG_FILE }}" | tee ~/.oci/config > /dev/null
          echo "${{ secrets.OCI_KEY_FILE }}" | tee ~/.oci/oci_api_key.pem > /dev/null
          chmod 600 ~/.oci/config ~/.oci/oci_api_key.pem
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest
      
      - name: Configure Terraform plugin cache
        run: |
          echo "TF_PLUGIN_CACHE_DIR=$HOME/.terraform.d/plugin-cache" >>"$GITHUB_ENV"
          mkdir --parents "$HOME/.terraform.d/plugin-cache"
          
      - name: Cache Terraform
        uses: actions/cache@v4
        with:
          path: |
            ~/.terraform.d/plugin-cache
          key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            terraform-${{ runner.os }}-

      - name: Terraform Init
        run: terraform init -backend-config="bucket=$BACKEND_CONFIG_BUCKET" -backend-config="namespace=$BACKEND_CONFIG_NAMESPACE" -backend-config="key=statefile/$TF_VAR_region/$TF_VAR_app_name/$TF_VAR_environment.tfstate"
        

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file="inputs/$TF_VAR_environment.tfvars" -out="tfplan-$TF_VAR_environment"

      - name: Cache Terraform Plan
        uses: actions/cache/save@v4
        with:
          path: tfplan-$TF_VAR_environment
          key: tfplan-${{ github.run_id }}-$TF_VAR_environment

  uat-apply:
    runs-on: ubuntu-latest
    needs: [uat-plan]
    environment: uat
    env:
      TF_VAR_environment: uat
      TF_VAR_compartment_ocid: ${{ secrets.TF_VAR_COMPARTMENT_OCID_UAT }}
      TF_VAR_app_name: ${{ vars.TF_VAR_APP_NAME }}
      TF_VAR_region: ${{ secrets.OCI_REGION }}
      BACKEND_CONFIG_BUCKET: ${{ secrets.BACKEND_CONFIG_BUCKET }}
      BACKEND_CONFIG_NAMESPACE: ${{ secrets.BACKEND_CONFIG_NAMESPACE }}

    steps:   
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Write Config & Key Files'
        run: |
          mkdir -p ~/.oci
          echo "${{ secrets.OCI_CONFIG_FILE }}" | tee ~/.oci/config > /dev/null
          echo "${{ secrets.OCI_KEY_FILE }}" | tee ~/.oci/oci_api_key.pem > /dev/null
          chmod 600 ~/.oci/config ~/.oci/oci_api_key.pem
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest
      
      - name: Configure Terraform plugin cache
        run: |
          echo "TF_PLUGIN_CACHE_DIR=$HOME/.terraform.d/plugin-cache" >>"$GITHUB_ENV"
          mkdir --parents "$HOME/.terraform.d/plugin-cache"
          
      - name: Cache Terraform
        uses: actions/cache@v4
        with:
          path: |
            ~/.terraform.d/plugin-cache
          key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            terraform-${{ runner.os }}-
      
      - name: Terraform Init
        run: terraform init -backend-config="bucket=$BACKEND_CONFIG_BUCKET" -backend-config="namespace=$BACKEND_CONFIG_NAMESPACE"  -backend-config="key=statefile/$TF_VAR_region/$TF_VAR_app_name/$TF_VAR_environment.tfstate"

      - name: Restore Plan Cache
        uses: actions/cache/restore@v4
        with:
          path: tfplan-$TF_VAR_environment
          key: tfplan-${{ github.run_id }}-$TF_VAR_environment
          fail-on-cache-miss: true

      - name: Terraform Apply
        run: terraform apply tfplan-$TF_VAR_environment
